const images = {
    landingPage: {
        New_Cap: "/assets/images/landingPage/New_cap.svg",
        heroSection: "/assets/images/landingPage/Home-left.jpg",
        risk: "/assets/images/landingPage/risk.png",
        access: "/assets/images/landingPage/access.png",
        briefcase: "/assets/images/landingPage/briefcase.png",
        server: "/assets/images/landingPage/server.png",
        BELEGGERSFAIR_LOGO_HEADER: "/assets/images/landingPage/BELEGGERSFAIR-LOGO-HEADER.png",
        IEX: "/assets/images/landingPage/IEX.png",
        rtlz: "/assets/images/landingPage/rtlz.png",
        IEX_nl: "/assets/images/landingPage/IEX_nl.png",
        Second: "/assets/images/landingPage/Second.png",
        Third: "/assets/images/landingPage/Third_logo.png",
        Forth: "/assets/images/landingPage/fourth_logo.png",
        Logo_five: "/assets/images/landingPage/Logo_five.png",
        Afm_disclaimer: "/assets/images/landingPage/Afm_disclaimer.png",
        B_class: "/assets/images/landingPage/class.png",
        heroSectionVideo: "/assets/images/landingPage/New hero animation.mp4",
        management: "/assets/images/landingPage/management.svg",
        handshake: "/assets/images/landingPage/handshake.png",
        schedule: "/assets/images/landingPage/schedule.png",
        dots_one: "/assets/images/landingPage/dots_one.png",
        dots_updated: "/assets/images/landingPage/Dot_updated.png",
        presentationPreview: "/assets/images/landingPage/presentationPreview.png",
        EC_businessclassThumbnail: "/assets/images/landingPage/Thumbnail.webp",
        Vid4Thumbnail: "/assets/images/landingPage/Vid4-thumbnail.png",
        teagan: "/assets/images/landingPage/teagan.png",
        paul: "/assets/images/landingPage/paul.png",
        scale: "/assets/images/landingPage/scale.png",
        Henk: "/assets/images/landingPage/Henk.png",
        Michiel: "/assets/images/landingPage/Michiel.png",
        Brahim: "/assets/images/landingPage/Brahim.png",
        Aron: "/assets/images/landingPage/Aron.webp",
        Pepijn: "/assets/images/landingPage/Pepijn.webp",
        Tom: "/assets/images/landingPage/Tom.webp",
        Bernard: "/assets/images/landingPage/Bernard.webp",
        rob: "/assets/images/landingPage/robb.png",
        money_briefcase: "/assets/images/landingPage/money-briefcase.png",
        profit: "/assets/images/landingPage/profit.svg",
        Brush: "/assets/images/landingPage/Brush.png",
        ECLogo: "/assets/images/ECLogo.png",
        ECLogoSVG: "/assets/images/ECLogo.svg",
        EdgeCapitalLogo: "/assets/images/EdgeCapitalLogo.png",
        EdgeCapitalLogoSVG: "/assets/images/EdgeCapitalLogo.svg",
        CrisisResilientIcon: "/assets/icons/crisis-resilient.svg",
        LimitedRiskIcon: "/assets/icons/limited-risk.svg",
        FlexibleIcon: "/assets/icons/flexible.svg",
        check_circle: "/assets/icons/check-circle.png",
        email: "/assets/icons/email.png",
        call: "/assets/icons/call.png",
        location: "/assets/icons/location.png",
        strategy: "/assets/icons/scale.png",
        bolt: "/assets/icons/bolt.png",
    },
    about: {
        herosectionforabout: "/assets/images/about/herosectionforabout.png",
    },
    edgefund: {
        edgehero: "/assets/images/edgefund/edgehero.png",
        edgehorizon: "/assets/images/edgefund/edgehorizon.png",
        edgecare: "/assets/images/edgefund/edgecare.png",
        effect: "/assets/images/edgefund/effect.png",
        scaleUp: "/assets/images/edgefund/scale.png",
        edgefundHero: "/assets/images/edgefund/Edgefund hero-img.jpg",
        aboutSide: "/assets/images/edgefund/About-edgefund-side.png",
        // grains: "/assets/images/grains.png", // This might duplicate existing /grains.svg?
    },
    edgeConnect: {
        Edge_Connect: "/assets/images/edgeconnect/Edge_Connect.webp",
        panda: "/assets/images/edgeconnect/panda.png",
        hartstiching: "/assets/images/edgeconnect/hartstiching.png",
        fork: "/assets/images/edgeconnect/fork.png",
        jant: "/assets/images/edgeconnect/jant.png",
        kika: "/assets/images/edgeconnect/kika.png",
        handshake_icon: "/assets/images/edgeconnect/handshake.png",
        network_icon: "/assets/images/edgeconnect/network.png",
        money_icon: "/assets/images/edgeconnect/money.png",
        clini: "/assets/images/edgeconnect/clini.png",
    },
    edgeCare: {
        edgecarehero: "/assets/images/edgecare/edgecarehero.webp",
    },
    institution: {
        researchdevelopment: "/assets/images/institution/researchdevelopment.png",
        researchIcon: "/assets/images/institution/research.png",
        MLIcon: "/assets/images/institution/MLIcon.png",
        tradingEngineIcon: "/assets/images/institution/tradingEngineIcon.png",
        directFundIcon: "/assets/images/institution/directFund.png",
        apiIcon: "/assets/images/institution/apiIcon.png",
        market_analysis: "/assets/images/institution/market_analysis.png",
        Clip_path: "/assets/images/institution/Clip_path.png",
        calculator: "/assets/images/institution/calculator.png",
        medal_award_badge: "/assets/images/institution/medal_award_badge.png",
        handshake_white: "/assets/images/institution/handshake_white.png",
        performance_basedIcon: "/assets/images/institution/performance_basedIcon.png",
        inHouse: "/assets/images/institution/inHouse.svg",
        ml: "/assets/images/institution/ml.svg",
        proprietary: "/assets/images/institution/proprietary.svg",
    },
    form: {
        inbox: "/assets/images/form/inbox.png",
        send_mail: "/assets/images/form/send_mail.png",
        flare: "/assets/images/form/flare.png",
        download: "/assets/images/form/download.png",
        career: "/assets/images/form/career.png",
    },
    edgeDoc: {
        document: "/assets/images/edgeDoc/document.png",
        person: "/assets/images/edgeDoc/person.png",
        discount_email: "/assets/images/edgeDoc/discount_email.png",
        form_submission: "/assets/images/edgeDoc/form_submission.png",
        security: "/assets/images/edgeDoc/security.png",
    },
    csr: {
        csrvid: "https://www.youtube.com/embed/OfOY6JoL63k?autoplay=1&mute=1&playsinline=1&controls=0&rel=0&loop=1&playlist=OfOY6JoL63k&modestbranding=1"
    },
    beleggersfair: {
        formBackground: "/assets/images/Belegger-bg.jpg",
        formImage: "/assets/images/Belegger-img.jpg",
        titleBrush: "/assets/images/Brush-uL.svg",
        formBackgroundMobile: "/assets/images/Bellgers-m-bg.jpg",
        heroBackground: "/assets/images/Beleggers-Hero-bg.jpg",
    },
}

export default images;
